export const itemsTechnology = [
  {
    id: '0',
    image: '/technologylist/html.webp',
    title: 'Html',
    link: 'https://html.com/',
  },
  {
    id: '1',
    image: '/technologylist/css.webp',
    title: 'Css',
    link: 'https://www.w3.org/Style/CSS/Overview.en.html',
  },
  {
    id: '2',
    image: '/technologylist/sass.webp',
    title: 'Sass',
    link: 'https://sass-lang.com/',
  },
  {
    id: '3',
    image: '/technologylist/js.webp',
    title: 'JavaScript',
    link: 'https://www.javascript.com/',
  },
  {
    id: '4',
    image: '/technologylist/ts.webp',
    title: 'TypeScript',
    link: 'https://www.typescriptlang.org/',
  },
  {
    id: '5',
    image: '/technologylist/react.webp',
    title: 'React',
    link: 'https://legacy.reactjs.org/',
  },
  {
    id: '6',
    image: '/technologylist/redux.webp',
    title: 'Redux',
    link: 'https://redux.js.org/',
  },
  {
    id: '7',
    image: '/technologylist/rtkquery.webp',
    title: 'RTK Query',
    link: 'https://redux-toolkit.js.org/rtk-query/overview',
  },
  {
    id: '8',
    image: '/technologylist/nextjs.webp',
    title: 'Next Js',
    link: 'https://nextjs.org/',
  },
  {
    id: '9',
    image: '/technologylist/nextauth.webp',
    title: 'Next Auth',
    link: 'https://next-auth.js.org/',
  },
  {
    id: '10',
    image: '/technologylist/serveractions.webp',
    title: 'Next Js Server Action',
    link: 'https://nextjs.org/docs/app/api-reference/functions/server-actions',
  },
  {
    id: '11',
    image: '/technologylist/node.webp',
    title: 'Node Js',
    link: 'https://nodejs.org/ru',
  },
  {
    id: '12',
    image: '/technologylist/handlebars.webp',
    title: 'Handlebars',
    link: 'https://handlebarsjs.com/',
  },
  {
    id: '13',
    image: '/technologylist/mongo.webp',
    title: 'Mongo DB',
    link: 'https://www.mongodb.com/',
  },
  {
    id: '14',
    image: '/technologylist/firebase.webp',
    title: 'Firebase',
    link: 'https://firebase.google.com/',
  },
  {
    id: '15',
    image: '/technologylist/parcel.webp',
    title: 'Parcel',
    link: 'https://parceljs.org/docs/',
  },
  {
    id: '16',
    image: '/technologylist/webpack.webp',
    title: 'Webpack',
    link: 'https://webpack.js.org/',
  },
  {
    id: '17',
    image: '/technologylist/vite.webp',
    title: 'Vite',
    link: 'https://vitejs.dev/',
  },
  {
    id: '18',
    image: '/technologylist/vsc.webp',
    title: 'VS Code',
    link: 'https://code.visualstudio.com/docs',
  },
  {
    id: '19',
    image: '/technologylist/github.webp',
    title: 'GitHub',
    link: 'https://docs.github.com/ru',
  },
  {
    id: '20',
    image: '/technologylist/figma.webp',
    title: 'Figma',
    link: 'https://help.figma.com/hc/en-us',
  },
  {
    id: '21',
    image: '/technologylist/photoshop.webp',
    title: 'Adobe Photoshop',
    link: 'https://www.adobe.com/products/photoshop/landpa.html?gclid=CjwKCAjwysipBhBXEiwApJOcu2MCc2df_XkGt-IjYMTT-Z5yxzepec7ZcwTML6-2z84SKP9ZMCAcTRoCLoMQAvD_BwE&sdid=KKQIN&mv=search&kw=photoshop&ef_id=CjwKCAjwysipBhBXEiwApJOcu2MCc2df_XkGt-IjYMTT-Z5yxzepec7ZcwTML6-2z84SKP9ZMCAcTRoCLoMQAvD_BwE:G:s&s_kwcid=AL!3085!3!673842496282!p!!g!!adobe%20photoshop!1712238397!67643563180&mv=search',
  },
];
