export const items = [
  {
    id: 1,
    title: 'Task pro',
    image: '/task-pro.png',
    additionalImages: [],
    description:
      'TaskProApp is a comprehensive task management web application developed with modern technologies. Our frontend is developed with React and a host of other libraries that work together to offer an exceptional user experience.The application allows an authorized user to create and manage tasks. Users can organize tasks into boards and columns, update them as needed, and even delete them. Furthermore, it supports choosing a custom background for the board and filtering tasks according to user requirements.Tasks are represented as cards and can be moved from one column to another to reflect their progress. If users encounter any difficulties, they can easily send a message to our support team through the provided form',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 2,
    title: 'Find pets',
    image: '/find-pets.png',
    additionalImages: [],
    description:
      'Animal Search Pet Project Welcome to the Animal Search Pet Project! This project is aimed at providing a platform for finding, selling, or giving animals to good homes. Users can search for animals, post listings, and connect with potential adopters or sellers. The application offers various features, including search filtering, sorting by title, news section, partners section, and a user account page for profile management and creating animal listings.',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 3,
    title: 'Social profile',
    image: '/social-profile.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 4,
    title: 'Filmoteka on react',
    image: '/filmoteka-react.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 5,
    title: 'filmoteka-js',
    image: '/filmoteka-js.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 6,
    title: 'filmoteka-js-version-1',
    image: '/filmoteka-version-1.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 7,
    title: 'Ice cream',
    image: '/icecream.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 8,
    title: 'Lifetour',
    image: '/lifetour.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 9,
    title: 'finance-ledger',
    image: '/finance-ledger.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
  {
    id: 10,
    title: 'Web studio',
    image: '/webstudio.png',
    additionalImages: [],
    description: 'Описание проекта Find Pets',
    website: 'https://example.com/task-pro',
    pageCode: 'https://github.com/example/task-pro',
  },
];
