import ReduxProvider from '../redux/ReduxProvider/Provider';
import LocalesProvider from '../locales/LocalesProvider/LocalesProvider';
import './globals.css';
import { Inter } from 'next/font/google';
import Header from '../components/Header/Header';
import NextAuthProvider from '../context/provider';
import Container from '../components/Container/Container';
import Copyright from '../components/Copyright/Copyright';
import UnderConstructionModal from '../components/UnderConstructionModal/UnderConstructionModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <LocalesProvider>
            <ReduxProvider>
              <Container>
                <Header />
                <UnderConstructionModal />
                <div className="container">
                  <main> {children}</main>
                </div>
              </Container>
              <Copyright />
            </ReduxProvider>
          </LocalesProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
