import Header from '../components/Header/Header';
import ReduxProvider from '../redux/ReduxProvider/Provider';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <div className="container">
            <main> {children}</main>
          </div>
        </body>
      </html>
    </ReduxProvider>
  );
}
